//      

                                                 

export const DEFAULT_CARD_SIZE = 200;

                                    
                  
                      
   

                                        
                 
                
                    
   

                                         
                                  
                                    
                                      
                               
                           
   

                               
               
                 
                                      
                                         
                
            
            
     
   

                                       
                  
                    
               
                     
   

                                            
                  
                         
                          
   

                                                          
