// flow-typed signature: f126c0d9614d4a5763349ee86c3c6f63
// flow-typed version: <<STUB>>/react-dnd_v14.0.2/flow_v0.150.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-dnd" {
  declare module.exports: any;
}
