// flow-typed signature: 444a25501e6ea0d3c2a570b9d0825e15
// flow-typed version: <<STUB>>/react-dnd-html5-backend_v14.0.0/flow_v0.150.0
// @flow
/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-html5-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-dnd-html5-backend" {
  declare export opaque type BackendFactory;
  declare export var HTML5Backend: BackendFactory;
}
